steps:
  # Step 0: Install MySQL dan ekstensi PHP di VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'rayhan-vm'
      - '--zone=asia-southeast2-a'
      - '--command=sudo apt-get update && sudo apt-get install -y mysql-server php-mysql && sudo systemctl restart apache2'

  # Step 1: Pull kode terbaru dari repo di direktori project
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'rayhan-vm'
      - '--zone=asia-southeast2-a'
      - '--command=cd /var/www/html/contact && git pull origin main'

  # Step 2: Import data.sql ke database MySQL
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'rayhan-vm'
      - '--zone=asia-southeast2-a'
      - '--command=sudo mysql -u root < /var/www/html/contact/data.sql'

# Set timeout build
timeout: '1200s'

# Konfigurasi logging dan service account
options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/kelompok-2-453402/serviceAccounts/rayhanschool20@kelompok-2-453402.iam.gserviceaccount.com
